definitions:
  financial_control_internal_user.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      name:
        type: string
    type: object
  internal_auth.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  internal_auth.LoginResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/financial_control_internal_user.UserResponse'
    type: object
  internal_auth.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  internal_transaction.Frequency:
    enum:
    - fixed
    - variable
    type: string
    x-enum-varnames:
    - Fixed
    - Variable
  internal_transaction.SummaryDTO:
    properties:
      balance:
        type: number
      total_expense:
        type: number
      total_income:
        type: number
    type: object
  internal_transaction.TransactionRequest:
    properties:
      amount:
        type: number
      category:
        type: string
      frequency:
        $ref: '#/definitions/internal_transaction.Frequency'
      title:
        type: string
      type:
        $ref: '#/definitions/internal_transaction.Type'
    required:
    - amount
    - title
    - type
    type: object
  internal_transaction.TransactionResponse:
    properties:
      amount:
        type: number
      category:
        type: string
      created_at:
        type: string
      frequency:
        $ref: '#/definitions/internal_transaction.Frequency'
      id:
        type: integer
      title:
        type: string
      type:
        $ref: '#/definitions/internal_transaction.Type'
      updated_at:
        type: string
    type: object
  internal_transaction.Type:
    enum:
    - income
    - expense
    type: string
    x-enum-varnames:
    - Income
    - Expense
  internal_user.CreateUserRequest:
    properties:
      email:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  internal_user.User:
    properties:
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      name:
        type: string
    type: object
  internal_user.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: Financial Control API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna JWT
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login de usuário
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: atualiza o token do usuario com nova data de expieração
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_auth.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh do token do usuario
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Cria um novo usuário no sistema
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Criar usuário
      tags:
      - Users
  /transaction:
    get:
      description: Retorna todas as transações
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_transaction.TransactionResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Lista transações
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: Cria uma nova transação no sistema
      parameters:
      - description: Transaction data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transaction.TransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Criar transação
      tags:
      - Transactions
  /transaction/{id}:
    delete:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Deletar transação
      tags:
      - Transactions
    get:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transaction.TransactionResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Buscar transação por ID
      tags:
      - Transactions
    put:
      consumes:
      - application/json
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transaction.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Atualizar transação
      tags:
      - Transactions
  /transaction/summary:
    get:
      parameters:
      - description: Mês (1-12)
        in: query
        name: month
        type: integer
      - description: 'Ano (ex: 2026)'
        in: query
        name: year
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transaction.SummaryDTO'
      security:
      - BearerAuth: []
      summary: Resumo das transações
      tags:
      - Transactions
  /user:
    get:
      description: Retorna todos os usuários
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_user.UserResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Lista usuários
      tags:
      - Users
  /user/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Deletar usuário
      tags:
      - Users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_user.UserResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Buscar usuário por ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Atualizar usuário
      tags:
      - Users
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_user.UserResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Retorna usuário logado
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: API para controle financeiro
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
