definitions:
  internal_user.CreateUserRequest:
    properties:
      email:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  internal_user.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  internal_user.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/internal_user.UserResponse'
    type: object
  internal_user.User:
    properties:
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      name:
        type: string
    type: object
  internal_user.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      login:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: Financial Control API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna JWT
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_user.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login de usuário
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Cria um novo usuário no sistema
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Criar usuário
      tags:
      - Users
  /user:
    get:
      description: Retorna todos os usuários
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_user.UserResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Lista usuários
      tags:
      - Users
  /user/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Deletar usuário
      tags:
      - Users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_user.UserResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Buscar usuário por ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Atualizar usuário
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: API para controle financeiro
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
